<?php
/**
 * Bolt magento2 plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 * @copyright  Copyright (c) 2018 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Shopping Cart page Bolt Checkout button
 *
 * @var $block \Bolt\Boltpay\Block\Js
 */
if ($block->shouldDisableBoltCheckout()) return;
?>
<div class="osc-place-order-block checkout-addition-block col-mp mp-12" style="width: 100%;text-align: initial;padding-bottom: 2rem;">
    <div class="osc-newsletter field choice col-mp mp-12">
        <input type="checkbox" checked="checked" name="bolt-newsletter" id="bolt-place-order-newsletter">
        <label for="id="><span>Register for newsletter</span></label>
    </div>
</div>
<div class="bolt-checkout-button bolt-multi-step-checkout <?=$block->getAdditionalCheckoutButtonClass(); ?>"></div>
